title: Vishesh's Blogs
author: Vishesh Mehta
email: mehtavishesh9795@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my first blog

# social links
github_username:  visheshm30 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima

